In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/Siddhi/CDAC/MachineLearning/housing_data_cleaned.csv")

In [4]:
df.head()

,bhk,area_sqft,age_years,floor,total_floors,parking_spaces,has_gym,has_pool,has_lift,price_lakhs
0,2,811.6,9.0,17,18,1,0,0,1,87.07
1,2,1134.7,9.0,13,18,1,0,1,1,203.16
2,1,464.9,1.0,2,10,1,1,1,1,73.45
3,4,3140.4,4.0,5,10,1,1,1,1,454.38
4,2,835.0,18.0,7,17,1,1,0,1,97.92

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score ,precision_score

In [7]:
x= df.drop(columns=['price_lakhs'])
y= df['price_lakhs']

In [8]:
x

,bhk,area_sqft,age_years,floor,total_floors,parking_spaces,has_gym,has_pool,has_lift
0,2,811.6,9.0,17,18,1,0,0,1
1,2,1134.7,9.0,13,18,1,0,1,1
2,1,464.9,1.0,2,10,1,1,1,1
3,4,3140.4,4.0,5,10,1,1,1,1
4,2,835.0,18.0,7,17,1,1,0,1
...,...,...,...,...,...,...,...,...,...
266,4,3259.4,1.0,15,24,1,1,0,1
267,3,1890.4,4.0,0,2,1,0,1,0
268,4,2354.6,10.0,0,2,0,0,0,0
269,3,1525.9,6.0,0,2,0,1,0,0
270,2,1091.6,18.0,16,22,1,1,0,1

In [9]:
y

0        87.07
1       203.16
2        73.45
3       454.38
4        97.92
        ...
266    1250.22
267     414.18
268     389.53
269     205.26
270      91.17
Name: price_lakhs, Length: 271, dtype: float64

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

NameError: name 'fit' is not defined